name = "minigame-gate"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "minigame-gate-db"
database_id = "4691fdc1-a749-4e97-a576-4dc56be2edf9"
migrations_dir = "migrations"
